### ISSUE TITLE
Installation failing 

### ISSUE THREAD

**Issue by Yvain-Desplat** [FEI38750/MTD#1]
Cloned the git as indicated and went on to the installation: 

bash ./MTD/Install.sh -t 60 -p ./miniconda

and the install throws error as shown in pictures below. 

Note that the clone and the miniconda are downloaded/installed in a mounted data storage where everything else is installed. I already have Kraken2 installed as well as other programs in there. 7.8To of free storage. 96 cores and 400 Go Ram Fedora Instance.

 What is the issue here ? 

![Screen Shot 2022-02-08 at 11 26 59 AM](https://user-images.githubusercontent.com/47155836/153060912-c3c0e856-88d7-4651-8338-206c3152f19f.png)
![Screen Shot 2022-02-08 at 11 26 25 AM](https://user-images.githubusercontent.com/47155836/153060914-76ea5ecf-45d9-4b8b-b4e3-7c0d782f5102.png)

**Comment by FEI38750** [comment]
Please try to use absolute path for conda, such as:
`bash MTD/Install.sh -t 60 -p ~/miniconda`

**Comment by Yvain-Desplat** [comment]
fixed some of the installation but still have an issue further down the process. Pything version installed is 3.8.5
thanks for the prompt response !  

![Screen Shot 2022-02-08 at 11 59 16 AM](https://user-images.githubusercontent.com/47155836/153066030-d276b2d0-b2a0-4e7b-b2c1-fa3083594b4e.png)

**Comment by FEI38750** [comment]
Um... Although it did not happen in my HPC environment, it may due to the install order of pip, which requires numpy installed before biom-format. Please try the updated install.sh and Installation/py2.yml.

**Comment by Yvain-Desplat** [comment]
UPDATE: whatever fix was done in the install.sh and py2.yml worked and installation was successful ! thank you for the reactivity and working fix !
